function paperSignificantPairwiseNoChunk(newResultsFile, oldXCFile)
% paperSignificantPairwiseNoChunk
%
% Paper plots for pairwise NO-CHUNK analysis.
%
% Uses TWO files:
%
% NEW RESULTS FILE:
%   results.sessions
%   R.actualPairStats.realVals
%   R.actualPairStats.lagVals
%   R.actualPairStats.sigFDRMask
%   R.actualSigLags
%   R.actualLagImbalance
%   R.nullLagImbalanceH0
%   R.nullCIH0
%
% OLD XC FILE:
%   allSessions.sessions
%   xcMatAll
%   lags
%   peakCorrMatAll
%   peakLagMatAll
%   nullCorrPrctile2p5
%   nullCorrPrctile97p5
%
% Produces:
%   A1. Example significant pair correlation vs. lag
%   A2. Example non-significant pair correlation vs. lag
%   C.  Distribution of peak lags for significant pairs
%   D.  Peak lag vs. peak correlation for significant pairs
%   E.  Lag imbalance relative to null distribution
%   F.  Summary of lag imbalance relative to null distribution
%
% Significance is ALWAYS determined from:
%   actualPairStats.sigFDRMask
%
% No old 3-SD criterion is used.
% No Bayes-factor quantities are used.
%
% D043 is excluded.
%
% Example-pair selection:
%   Significant example:
%       significant pair with largest peak correlation
%
%   Non-significant example:
%       RANDOM valid pair that was not Storey/FDR significant
%
% For A1 and A2, the displayed peak correlation and peak lag are
% calculated directly from the exact xcMatAll curve being plotted.
% This guarantees that the red peak marker and peak-lag line coincide
% with the actual maximum of the displayed XC curve.

arguments
    newResultsFile (1,1) string = ...
        "C:\Users\mirilab\Documents\GlobusTransfer\pairwiseNoChunkLagImbalanceBayes50ms_StoreyCorrThresh_DAVID_UPDATE.mat"

    oldXCFile (1,1) string = ...
        "C:\Users\mirilab\Documents\GlobusTransfer\pairwise_nochunk_allPairs_ALL_SESSIONS_COMBINED.mat"
end

%% ========================================================================
%% FORMATTING
%% ========================================================================

fontSize = 10;
axesLineWidth = 0.5;
tickLength = [0.025 0.025];

saveDir = ...
    "X:\David\AnalysesData\InterneuronAnalyses\AA Paper Plots\pairwise no-chunk";

if ~exist(saveDir, 'dir')
    mkdir(saveDir);
end

%% ========================================================================
%% LOAD NEW RESULTS
%% ========================================================================

Snew = load(newResultsFile, 'results');

if ~isfield(Snew, 'results')
    error('New file does not contain variable "results".');
end

results = Snew.results;

if ~isfield(results, 'sessions') || isempty(results.sessions)
    error('results.sessions is missing or empty.');
end

newSessions = results.sessions;

%% ========================================================================
%% LOAD OLD FULL-XC RESULTS
%% ========================================================================

Sold = load(oldXCFile, 'allSessions');

if ~isfield(Sold, 'allSessions')
    error('Old file does not contain variable "allSessions".');
end

allSessions = Sold.allSessions;

if ~isfield(allSessions, 'sessions') || isempty(allSessions.sessions)
    error('allSessions.sessions is missing or empty.');
end

oldSessions = allSessions.sessions;

%% ========================================================================
%% COLLECT VALID ANIMALS
%% ========================================================================

animalIDs = strings(0,1);
newData = cell(0,1);
oldData = cell(0,1);

for s = 1:numel(newSessions)

    if iscell(newSessions)
        R = newSessions{s};
    else
        R = newSessions(s);
    end

    if isempty(R)
        continue;
    end

    if isfield(R,'animalID') && ~isempty(R.animalID)
        animalID = string(R.animalID);
    else
        animalID = "Animal_" + s;
    end

    % Exclude D043
    if strcmpi(animalID,"D043")
        continue;
    end

    %% ---- find matching session in old file ----

    oldMatch = [];

    for q = 1:numel(oldSessions)

        O = oldSessions(q);

        if isfield(O,'mouseID') && ...
                strcmpi(string(O.mouseID),animalID)

            oldMatch = O;
            break;
        end
    end

    if isempty(oldMatch)
        warning('%s: no matching session found in old XC file.',animalID);
        continue;
    end

    animalIDs(end+1,1) = animalID; %#ok<AGROW>
    newData{end+1,1} = R; %#ok<AGROW>
    oldData{end+1,1} = oldMatch; %#ok<AGROW>
end

nAnimals = numel(animalIDs);

if nAnimals == 0
    error('No matched animals remain after filtering.');
end

%% ========================================================================
%% STORAGE FOR SUMMARY PLOT F
%% ========================================================================

actualImbalanceAll = nan(nAnimals,1);
nullLowAll = nan(nAnimals,1);
nullHighAll = nan(nAnimals,1);

%% ========================================================================
%% LOOP THROUGH ANIMALS
%% ========================================================================

for s = 1:nAnimals

    animalID = animalIDs(s);

    R = newData{s};
    O = oldData{s};

    P = R.actualPairStats;

    %% ====================================================================
    %% PAIRWISE DATA
    %% ====================================================================

    rows = P.rows(:);
    cols = P.cols(:);

    allCorrVec = P.realVals(:);
    allLagVec = P.lagVals(:);

    sigMask = logical(P.sigFDRMask(:));

    validMask = ...
        isfinite(rows) & ...
        isfinite(cols) & ...
        isfinite(allCorrVec) & ...
        isfinite(allLagVec);

    sigValidMask = ...
        sigMask & validMask;

    nonsigValidMask = ...
        ~sigMask & validMask;

    sigCorrVec = allCorrVec(sigValidMask);
    sigLagVec = allLagVec(sigValidMask);

    actualLagImbalance = R.actualLagImbalance;

    nullLagImbalance = R.nullLagImbalanceH0(:);
    nullLagImbalance = ...
        nullLagImbalance(isfinite(nullLagImbalance));

    nullCI = R.nullCIH0(:);

    actualImbalanceAll(s) = actualLagImbalance;
    nullLowAll(s) = nullCI(1);
    nullHighAll(s) = nullCI(2);

    fprintf('\n========================================\n');
    fprintf('%s\n',animalID);
    fprintf('========================================\n');

    fprintf('Total tested pairs: %d\n',numel(allCorrVec));
    fprintf('Significant pairs: %d\n',sum(sigValidMask));
    fprintf('Non-significant pairs: %d\n',sum(nonsigValidMask));
    fprintf('Lag imbalance: %.6f\n',actualLagImbalance);

    %% ====================================================================
    %% A1 — EXAMPLE SIGNIFICANT PAIR
    %% ====================================================================

    sigIndices = find(sigValidMask);

    if ~isempty(sigIndices)

        % Choose significant pair with largest saved peak correlation.
        % Significance and pair selection still come from Storey/FDR.
        [~,ii] = max(allCorrVec(sigIndices));
        pairInd = sigIndices(ii);

        row = rows(pairInd);
        col = cols(pairInd);

        xcCurve = squeeze(O.xcMatAll(row,col,:));
        lagAxis = O.lags(:);

        % ---------------------------------------------------------------
        % Find the actual peak directly from the exact XC curve plotted.
        % ---------------------------------------------------------------
        validXC = isfinite(xcCurve) & isfinite(lagAxis);

        if ~any(validXC)

            warning( ...
                '%s significant pair (%d,%d) has no finite XC values.', ...
                animalID,row,col);

        else

            validInds = find(validXC);

            [peakCorr,localPeakIdx] = max(xcCurve(validXC));

            peakIdx = validInds(localPeakIdx);
            peakLag = lagAxis(peakIdx);

            lowerBound = O.nullCorrPrctile2p5(row,col);
            upperBound = O.nullCorrPrctile97p5(row,col);

            fprintf(['Significant example: row %d, col %d | ' ...
                'plotted XC peak corr = %.6f | ' ...
                'plotted XC peak lag = %.6f s\n'], ...
                row,col,peakCorr,peakLag);

            figA1 = figure( ...
                'Name', ...
                sprintf('%s example significant pair correlation vs. lag', ...
                animalID), ...
                'Color','w');

            ax = axes(figA1);
            hold(ax,'on');

            %% XC curve
            hXC = plot( ...
                ax, ...
                lagAxis, ...
                xcCurve, ...
                '-', ...
                'LineWidth',1);

            %% 95% null bounds
            hBound = yline( ...
                ax, ...
                upperBound, ...
                '--', ...
                'LineWidth',axesLineWidth);

            yline( ...
                ax, ...
                lowerBound, ...
                '--', ...
                'LineWidth',axesLineWidth);

            %% Peak lag
            hPeakLag = xline( ...
                ax, ...
                peakLag, ...
                'r:', ...
                'LineWidth',1);

            %% Peak correlation
            hPeakCorr = plot( ...
                ax, ...
                peakLag, ...
                peakCorr, ...
                'ro', ...
                'MarkerFaceColor','r', ...
                'MarkerEdgeColor','r', ...
                'MarkerSize',5);

            xlabel( ...
                ax, ...
                'Lag (seconds)', ...
                'FontSize',fontSize);

            ylabel( ...
                ax, ...
                'Correlation', ...
                'FontSize',fontSize);

            title( ...
                ax, ...
                sprintf('%s example significant pair correlation vs. lag', ...
                animalID), ...
                'FontSize',fontSize);

            legend( ...
                ax, ...
                [hXC hPeakLag hPeakCorr hBound], ...
                {'Example pair XC', ...
                 'Peak lag', ...
                 'Peak correlation', ...
                 '95% shift-control bounds'}, ...
                'Location','best', ...
                'FontSize',fontSize);

            set( ...
                ax, ...
                'FontSize',fontSize, ...
                'LineWidth',axesLineWidth, ...
                'TickDir','out', ...
                'TickLength',tickLength, ...
                'XColor','k', ...
                'YColor','k');

            grid(ax,'off');
            box(ax,'off');

            exportgraphics( ...
                figA1, ...
                fullfile( ...
                    saveDir, ...
                    sprintf('%s_example_significant_pair_xcorr.pdf', ...
                    animalID)), ...
                'ContentType','vector', ...
                'BackgroundColor','white');

        end
    end

    %% ====================================================================
    %% A2 — RANDOM EXAMPLE NON-SIGNIFICANT PAIR
    %% ====================================================================

    nonsigIndices = find(nonsigValidMask);

    if ~isempty(nonsigIndices)

        % RANDOMLY select one valid pair that was NOT significant.
        randomPosition = randi(numel(nonsigIndices));
        pairInd = nonsigIndices(randomPosition);

        row = rows(pairInd);
        col = cols(pairInd);

        xcCurve = squeeze(O.xcMatAll(row,col,:));
        lagAxis = O.lags(:);

        % ---------------------------------------------------------------
        % Find the actual peak directly from the exact XC curve plotted.
        % ---------------------------------------------------------------
        validXC = isfinite(xcCurve) & isfinite(lagAxis);

        if ~any(validXC)

            warning( ...
                '%s non-significant pair (%d,%d) has no finite XC values.', ...
                animalID,row,col);

        else

            validInds = find(validXC);

            [peakCorr,localPeakIdx] = max(xcCurve(validXC));

            peakIdx = validInds(localPeakIdx);
            peakLag = lagAxis(peakIdx);

            lowerBound = O.nullCorrPrctile2p5(row,col);
            upperBound = O.nullCorrPrctile97p5(row,col);

            fprintf(['Random non-significant example: row %d, col %d | ' ...
                'plotted XC peak corr = %.6f | ' ...
                'plotted XC peak lag = %.6f s\n'], ...
                row,col,peakCorr,peakLag);

            figA2 = figure( ...
                'Name', ...
                sprintf('%s example non-significant pair correlation vs. lag', ...
                animalID), ...
                'Color','w');

            ax = axes(figA2);
            hold(ax,'on');

            %% XC curve
            hXC = plot( ...
                ax, ...
                lagAxis, ...
                xcCurve, ...
                '-', ...
                'LineWidth',1);

            %% 95% null bounds
            hBound = yline( ...
                ax, ...
                upperBound, ...
                '--', ...
                'LineWidth',axesLineWidth);

            yline( ...
                ax, ...
                lowerBound, ...
                '--', ...
                'LineWidth',axesLineWidth);

            %% Peak lag
            hPeakLag = xline( ...
                ax, ...
                peakLag, ...
                'r:', ...
                'LineWidth',1);

            %% Peak correlation
            hPeakCorr = plot( ...
                ax, ...
                peakLag, ...
                peakCorr, ...
                'ro', ...
                'MarkerFaceColor','r', ...
                'MarkerEdgeColor','r', ...
                'MarkerSize',5);

            xlabel( ...
                ax, ...
                'Lag (seconds)', ...
                'FontSize',fontSize);

            ylabel( ...
                ax, ...
                'Correlation', ...
                'FontSize',fontSize);

            title( ...
                ax, ...
                sprintf('%s example non-significant pair correlation vs. lag', ...
                animalID), ...
                'FontSize',fontSize);

            legend( ...
                ax, ...
                [hXC hPeakLag hPeakCorr hBound], ...
                {'Example pair XC', ...
                 'Peak lag', ...
                 'Peak correlation', ...
                 '95% shift-control bounds'}, ...
                'Location','best', ...
                'FontSize',fontSize);

            set( ...
                ax, ...
                'FontSize',fontSize, ...
                'LineWidth',axesLineWidth, ...
                'TickDir','out', ...
                'TickLength',tickLength, ...
                'XColor','k', ...
                'YColor','k');

            grid(ax,'off');
            box(ax,'off');

            exportgraphics( ...
                figA2, ...
                fullfile( ...
                    saveDir, ...
                    sprintf('%s_example_nonsignificant_pair_xcorr.pdf', ...
                    animalID)), ...
                'ContentType','vector', ...
                'BackgroundColor','white');

        end
    end

    %% ====================================================================
    %% C — DISTRIBUTION OF PEAK LAGS FOR SIGNIFICANT PAIRS
    %% ====================================================================

    figC = figure( ...
        'Name', ...
        sprintf('%s distribution of peak lags for significant pairs', ...
        animalID), ...
        'Color','w');

    ax = axes(figC);
    hold(ax,'on');

    % 1-ms bins over +/-300 ms.
    lagEdges = -0.300:0.001:0.300;

    hHist = histogram( ...
        ax, ...
        sigLagVec, ...
        'BinEdges',lagEdges, ...
        'EdgeColor','none');

    hZero = xline( ...
        ax, ...
        0, ...
        '--', ...
        'LineWidth',axesLineWidth);

    xlim(ax,[-0.3 0.3]);

    xlabel( ...
        ax, ...
        'Peak lag (seconds)', ...
        'FontSize',fontSize);

    ylabel( ...
        ax, ...
        'Pair count', ...
        'FontSize',fontSize);

    title( ...
        ax, ...
        sprintf('%s distribution of peak lags for significant pairs', ...
        animalID), ...
        'FontSize',fontSize);

    legend( ...
        ax, ...
        [hHist hZero], ...
        {sprintf('Lag imbalance = %.3f',actualLagImbalance), ...
         'Zero lag reference'}, ...
        'Location','best', ...
        'FontSize',fontSize);

    set( ...
        ax, ...
        'FontSize',fontSize, ...
        'LineWidth',axesLineWidth, ...
        'TickDir','out', ...
        'TickLength',tickLength, ...
        'XColor','k', ...
        'YColor','k');

    grid(ax,'off');
    box(ax,'off');

    exportgraphics( ...
        figC, ...
        fullfile( ...
            saveDir, ...
            sprintf('%s_significant_peak_lag_distribution.pdf',animalID)), ...
        'ContentType','vector', ...
        'BackgroundColor','white');

    %% ====================================================================
    %% D — PEAK LAG VS. PEAK CORRELATION FOR SIGNIFICANT PAIRS
    %% ====================================================================

    if ~isempty(sigLagVec)

        figD = figure( ...
            'Name', ...
            sprintf('%s peak lag vs. peak correlation for significant pairs', ...
            animalID), ...
            'Color','w');

        h = scatterhist( ...
            sigLagVec(:), ...
            sigCorrVec(:), ...
            'Direction','out', ...
            'Marker','.');

        axMain = h(1);

        xlabel( ...
            axMain, ...
            'Peak lag (seconds)', ...
            'FontSize',fontSize);

        ylabel( ...
            axMain, ...
            'Peak correlation', ...
            'FontSize',fontSize);

        title( ...
            axMain, ...
            sprintf('%s peak lag vs. peak correlation for significant pairs', ...
            animalID), ...
            'FontSize',fontSize);

        xlim(axMain,[-0.3 0.3]);

        hold(axMain,'on');

        if isfield(P,'corrThresh') && ...
                ~isempty(P.corrThresh) && ...
                isfinite(P.corrThresh)

            hThresh = yline( ...
                axMain, ...
                P.corrThresh, ...
                '--', ...
                'LineWidth',axesLineWidth);

            legend( ...
                axMain, ...
                hThresh, ...
                'Correlation threshold', ...
                'Location','best', ...
                'FontSize',fontSize);
        end

        for a = 1:numel(h)

            if isgraphics(h(a),'axes')

                set( ...
                    h(a), ...
                    'FontSize',fontSize, ...
                    'LineWidth',axesLineWidth, ...
                    'TickDir','out', ...
                    'TickLength',tickLength, ...
                    'XColor','k', ...
                    'YColor','k');

                grid(h(a),'off');
                box(h(a),'off');
            end
        end

        exportgraphics( ...
            figD, ...
            fullfile( ...
                saveDir, ...
                sprintf('%s_peak_lag_vs_peak_corr.pdf',animalID)), ...
            'ContentType','vector', ...
            'BackgroundColor','white');
    end

    %% ====================================================================
    %% E — LAG IMBALANCE RELATIVE TO NULL DISTRIBUTION
    %% ====================================================================

    figE = figure( ...
        'Name', ...
        sprintf('%s lag imbalance relative to null distribution',animalID), ...
        'Color','w');

    ax = axes(figE);
    hold(ax,'on');

    hNull = histogram( ...
        ax, ...
        nullLagImbalance, ...
        20, ...
        'EdgeColor','none');

    hActual = xline( ...
        ax, ...
        actualLagImbalance, ...
        'r-', ...
        'LineWidth',1.25);

    hCI = xline( ...
        ax, ...
        nullCI(1), ...
        '--', ...
        'LineWidth',axesLineWidth);

    xline( ...
        ax, ...
        nullCI(2), ...
        '--', ...
        'LineWidth',axesLineWidth);

    xlabel( ...
        ax, ...
        'Lag imbalance', ...
        'FontSize',fontSize);

    ylabel( ...
        ax, ...
        'Count', ...
        'FontSize',fontSize);

    title( ...
        ax, ...
        sprintf('%s lag imbalance relative to null distribution',animalID), ...
        'FontSize',fontSize);

    legend( ...
        ax, ...
        [hNull hActual hCI], ...
        {'Null lag imbalance distribution', ...
         sprintf('Actual lag imbalance = %.3f',actualLagImbalance), ...
         '95% null interval'}, ...
        'Location','best', ...
        'FontSize',fontSize);

    set( ...
        ax, ...
        'FontSize',fontSize, ...
        'LineWidth',axesLineWidth, ...
        'TickDir','out', ...
        'TickLength',tickLength, ...
        'XColor','k', ...
        'YColor','k');

    grid(ax,'off');
    box(ax,'off');

    exportgraphics( ...
        figE, ...
        fullfile( ...
            saveDir, ...
            sprintf('%s_lag_imbalance_null_distribution.pdf',animalID)), ...
        'ContentType','vector', ...
        'BackgroundColor','white');

end

%% ========================================================================
%% F — SUMMARY OF LAG IMBALANCE RELATIVE TO NULL DISTRIBUTION
%% ========================================================================

figF = figure( ...
    'Name', ...
    'Summary of lag imbalance relative to null distribution', ...
    'Color','w', ...
    'Position',[100 100 1500 650]);

ax = axes(figF);
hold(ax,'on');

x = 1:nAnimals;

%% ---- zero reference ----

hZero = yline( ...
    ax, ...
    0, ...
    ':', ...
    'LineWidth',axesLineWidth);

%% ---- 95% null intervals ----
%
% Plot each interval directly from nullLowAll to nullHighAll.
% All null interval bars and caps are gray.

hCI = gobjects(nAnimals,1);

grayColor = [0.5 0.5 0.5];

for s = 1:nAnimals

    hCI(s) = plot( ...
        ax, ...
        [x(s) x(s)], ...
        [nullLowAll(s) nullHighAll(s)], ...
        '-', ...
        'Color',grayColor, ...
        'LineWidth',1.25);

    % Small horizontal caps
    plot( ...
        ax, ...
        [x(s)-0.08 x(s)+0.08], ...
        [nullLowAll(s) nullLowAll(s)], ...
        '-', ...
        'Color',grayColor, ...
        'LineWidth',1.25, ...
        'HandleVisibility','off');

    plot( ...
        ax, ...
        [x(s)-0.08 x(s)+0.08], ...
        [nullHighAll(s) nullHighAll(s)], ...
        '-', ...
        'Color',grayColor, ...
        'LineWidth',1.25, ...
        'HandleVisibility','off');
end

%% ---- actual lag imbalance ----

hActual = plot( ...
    ax, ...
    x, ...
    actualImbalanceAll, ...
    'ko', ...
    'LineStyle','none', ...
    'MarkerFaceColor','k', ...
    'MarkerEdgeColor','k', ...
    'MarkerSize',5);

xlim(ax,[0.5 nAnimals+0.5]);

xticks(ax,x);
xticklabels(ax,animalIDs);

xlabel( ...
    ax, ...
    'Animal', ...
    'FontSize',fontSize);

ylabel( ...
    ax, ...
    'Lag imbalance', ...
    'FontSize',fontSize);

title( ...
    ax, ...
    'Summary of lag imbalance relative to null distribution', ...
    'FontSize',fontSize);

legend( ...
    ax, ...
    [hActual hCI(1) hZero], ...
    {'Actual lag imbalance', ...
     '95% null interval', ...
     'Zero lag reference'}, ...
    'Location','best', ...
    'FontSize',fontSize);

set( ...
    ax, ...
    'FontSize',fontSize, ...
    'LineWidth',axesLineWidth, ...
    'TickDir','out', ...
    'TickLength',tickLength, ...
    'XColor','k', ...
    'YColor','k');

grid(ax,'off');
box(ax,'off');

exportgraphics( ...
    figF, ...
    fullfile( ...
        saveDir, ...
        'summary_lag_imbalance_relative_to_null.pdf'), ...
    'ContentType','vector', ...
    'BackgroundColor','white');

fprintf('\n========================================\n');
fprintf('All pairwise no-chunk paper plots saved to:\n');
fprintf('%s\n',saveDir);
fprintf('========================================\n');

end
