function runNonChunkedXcorrPerBehavior_saveOnly(baseDirs, labelType, behaviors, maxLagSecs, numShifts, numPerms)
% non-chunked (full time series) cross-correlation between cortex interneuron and pyramidal population activity, computed separately within each behavior label type

% save-only version:
%   - computes everything
%   - saves all plotting-ready outputs
%   - does not make figures

% important: this is NOT event-centered like chunked
% it restricts to timepoints belonging to a behavior and computes xc(lag) over those behavior-specific vectors

% updated fix:
%   - shifted control correlations are now generated by shifting the FULL
%     session-length interneuron population trace first, then restricting
%     that shifted trace to the behavior timepoints
%   - this makes the null logic more consistent with the chunked analysis
%     and avoids requiring each behavior to be >= ~60 s long just to allow
%     a 30 s minimum shift

% this updated version is classifier-only to avoid loading unused variables from UMAP.mat

% inputs:
%   baseDirs : cell array of ProcessedData folders (one per animal/session)
%   labelType : must be "classifier"
%   behaviors : vector of behaviors to compute (default 0:10)
%   maxLagSecs : max lag in seconds (default 0.5)
%   numShifts : circular-shift null draws for correlation bounds (default 100)
%   numPerms : label-permutation draws for lag ci (default 100)

% output:
%   - one saved .mat file containing everything needed to replot later

% example:
%   baseDirs = {
%     'X:\David\ArenaRecordings\D026-032923-ArenaRecording\ProcessedData', ...
%     'Z:\David\ArenaRecordings\NeuropixelsTest\D020-062922-ArenaRecording\ProcessedData', ...
%     'Z:\David\ArenaRecordings\NeuropixelsTest\D024-111022-ArenaRecording\ProcessedData', ...
%     'X:\David\ArenaRecordings\D043-020525-ArenaRecording\ProcessedData'
%   };
%   runNonChunkedXcorrPerBehavior_saveOnly(baseDirs, "classifier", 0:10, 0.5, 100, 100);

    if nargin < 2 || isempty(labelType),  labelType = "classifier"; end
    labelType = lower(string(labelType));

    if labelType ~= "classifier"
        error('this updated version only supports labelType = "classifier".');
    end

    if nargin < 4 || isempty(maxLagSecs), maxLagSecs = 0.5; end
    if nargin < 5 || isempty(numShifts),  numShifts  = 100; end
    if nargin < 6 || isempty(numPerms),   numPerms   = 100; end

    if nargin < 3 || isempty(behaviors)
        behaviors = 0:10;
    end

    binSize = 0.001;  % 1 ms bins
    nSess   = numel(baseDirs);
    nB      = numel(behaviors);

    % load centralized classifications file
    conslidatedDataFoler = 'X:\David\AnalysesData';
    load(fullfile(conslidatedDataFoler, 'AA_classifications.mat'), 'classifications');

    % known base folders (match AA_classifications row order)
    animalFolders = {
        'X:\David\ArenaRecordings\D026-032923-ArenaRecording\ProcessedData', ...
        'Z:\David\ArenaRecordings\NeuropixelsTest\D020-062922-ArenaRecording\ProcessedData', ...
        'Z:\David\ArenaRecordings\NeuropixelsTest\D024-111022-ArenaRecording\ProcessedData', ...
        'X:\David\ArenaRecordings\D043-020525-ArenaRecording\ProcessedData'
    };

    % master output struct
    results = struct();
    results.baseDirs = baseDirs;
    results.labelType = labelType;
    results.behaviors = behaviors;
    results.binSize = binSize;
    results.maxLagSecs = maxLagSecs;
    results.numShifts = numShifts;
    results.numPerms = numPerms;
    results.sessions = repmat(struct( ...
        'baseDir', '', ...
        'sessionTag', '', ...
        'meta', struct(), ...
        'beh', []), 1, nSess);

    for iDir = 1:nSess
        baseDir = baseDirs{iDir};
        fprintf('\n=== processing session %d/%d: %s ===\n', iDir, nSess, baseDir);

        frFile = fullfile(baseDir, 'NeuralFiringRates1msBins10msGauss.mat');
        if ~isfile(frFile)
            warning('missing firing rate file in %s. skipping.', baseDir);
            continue;
        end

        % load cortex firing rates + inds
        F = load(frFile, 'cortexFRs', 'cortexInds');
        cortexFRs  = F.cortexFRs;
        cortexInds = F.cortexInds(:);

        frMatrix = cortexFRs; % neurons x time
        regionInds = cortexInds; % neuronDataStruct indices for cortex units
        Tfr = size(frMatrix, 2);

        % match classifications row
        matchRow = find(contains(animalFolders, baseDir), 1);
        if isempty(matchRow)
            warning('could not match baseDir to animalFolders list. skipping.');
            continue;
        end

        % cortex is iRegion = 1
        iRegion = 1;
        neuronType = classifications{matchRow, iRegion}; % 1=int, 0=pyr
        if isempty(neuronType)
            warning('no classification data for %s. skipping.', baseDir);
            continue;
        end

        regionClass = neuronType(regionInds);

        intFRs = frMatrix(regionClass == 1, :);
        pyrFRs = frMatrix(regionClass == 0, :);

        if isempty(intFRs) || isempty(pyrFRs)
            warning('no valid int/pyr cortex units for %s. skipping.', baseDir);
            continue;
        end

        % population means across neurons
        meanIntRaw = mean(intFRs, 1, 'omitnan');
        meanPyrRaw = mean(pyrFRs, 1, 'omitnan');

        % build full-length behavior vector aligned to fr time base
        [labels1k, meta] = buildTimepointBehaviorLabels(baseDir, Tfr, labelType);

        % session output
        out = struct();
        out.baseDir = baseDir;
        out.labelType = labelType;
        out.behaviors = behaviors;
        out.binSize = binSize;
        out.maxLagSecs = maxLagSecs;
        out.numShifts = numShifts;
        out.numPerms = numPerms;
        out.meta = meta;

        out.beh = repmat(struct( ...
            'beh', [], ...
            'nTimepoints', [], ...
            'timeIdx', [], ...
            'lagsSec', [], ...
            'xc', [], ...
            'peakLagSec', [], ...
            'peakCorr', [], ...
            'ctrlCorrs', [], ...
            'ctrlCorrCI', [], ...
            'permPeakLags', [], ...
            'lagCI', []), 1, nB);

        for bIdx = 1:nB
            beh = behaviors(bIdx);

            timeIdx = find(labels1k == beh);
            if isempty(timeIdx)
                out.beh(bIdx).beh = beh;
                out.beh(bIdx).nTimepoints = 0;
                continue;
            end

            % restrict real signals to this behavior
            intVec = meanIntRaw(timeIdx);
            pyrVec = meanPyrRaw(timeIdx);

            % compute real xc(lag)
            [lagsSec, xc, peakLag, peakCorr] = computeManualXCorrVec(intVec, pyrVec, binSize, maxLagSecs);

            % ============================================================
            % control distribution for correlation bounds (circular shifts)
            % FIXED VERSION:
            %   shift the FULL session-length int trace first
            %   then restrict the shifted trace to behavior timepoints
            % ============================================================
            ctrlCorrs = nan(1, numShifts);
            minShiftBins = round(30 / binSize); % 30 sec minimum shift
            maxShiftBinsOk = numel(meanIntRaw) - minShiftBins;

            if maxShiftBinsOk >= minShiftBins
                for s = 1:numShifts
                    shiftAmt = randi([minShiftBins, maxShiftBinsOk]);

                    % shift full session first
                    intShiftFull = circshift(meanIntRaw, shiftAmt);

                    % then restrict shifted full trace to this behavior
                    intShiftVec = intShiftFull(timeIdx);

                    v = ~isnan(intShiftVec) & ~isnan(pyrVec);
                    if nnz(v) > 10
                        x = intShiftVec(v);
                        y = pyrVec(v);
                        ctrlCorrs(s) = corr(x(:), y(:));
                    end
                end

                goodCtrl = isfinite(ctrlCorrs) & ~isnan(ctrlCorrs);
                if any(goodCtrl)
                    ctrlCI = prctile(ctrlCorrs(goodCtrl), [2.5 97.5]);
                else
                    ctrlCI = [NaN NaN];
                end
            else
                ctrlCI = [NaN NaN];
            end

            % ============================================================
            % permutation distribution for lag
            % shuffle neuron labels within cortex
            % ============================================================
            permPeakLags = nan(1, numPerms);
            for p = 1:numPerms
                permLabels = regionClass(randperm(numel(regionClass)));
                permIntFRs = frMatrix(permLabels == 1, :);
                permPyrFRs = frMatrix(permLabels == 0, :);

                if isempty(permIntFRs) || isempty(permPyrFRs)
                    continue;
                end

                permMeanInt = mean(permIntFRs, 1, 'omitnan');
                permMeanPyr = mean(permPyrFRs, 1, 'omitnan');

                permIntVec = permMeanInt(timeIdx);
                permPyrVec = permMeanPyr(timeIdx);

                [~, ~, permPeakLag, ~] = computeManualXCorrVec(permIntVec, permPyrVec, binSize, maxLagSecs);
                permPeakLags(p) = permPeakLag;
            end

            goodPerm = ~isnan(permPeakLags);
            if any(goodPerm)
                lagCI = prctile(permPeakLags(goodPerm), [2.5 97.5]);
            else
                lagCI = [NaN NaN];
            end

            % store outputs
            out.beh(bIdx).beh = beh;
            out.beh(bIdx).nTimepoints = numel(timeIdx);
            out.beh(bIdx).timeIdx = timeIdx;
            out.beh(bIdx).lagsSec = lagsSec;
            out.beh(bIdx).xc = xc;
            out.beh(bIdx).peakLagSec = peakLag;
            out.beh(bIdx).peakCorr = peakCorr;
            out.beh(bIdx).ctrlCorrs = ctrlCorrs;
            out.beh(bIdx).ctrlCorrCI = ctrlCI;
            out.beh(bIdx).permPeakLags = permPeakLags(goodPerm);
            out.beh(bIdx).lagCI = lagCI;
        end

        results.sessions(iDir).baseDir = baseDir;
        results.sessions(iDir).sessionTag = shortTag(baseDir);
        results.sessions(iDir).meta = meta;
        results.sessions(iDir).beh = out.beh;
    end

    savePath = fullfile(conslidatedDataFoler, sprintf('nonchunked_xcorr_by_%s_cortex_allSessions_saved.mat', labelType));
    save(savePath, 'results', '-v7.3');
    fprintf('\nsaved plotting-ready outputs: %s\n', savePath);
end

% =====================================================================
% helper: build full-length timepoint behavior labels aligned to fr bins
% classifier-only version
% =====================================================================
function [labels1k, meta] = buildTimepointBehaviorLabels(baseDir, Tfr, labelType)
% outputs:
%   labels1k: 1 x Tfr vector with labels (classifier: 0..10), nan if unknown
%   meta: struct with mapping info and canonical names

    labelType = lower(string(labelType));
    meta = struct();
    meta.labelType = labelType;

    labels1k = nan(1, Tfr);

    if labelType ~= "classifier"
        error('this version of buildTimepointBehaviorLabels only supports "classifier".');
    end

    umapFile = fullfile(baseDir, 'UMAP.mat');
    if ~isfile(umapFile)
        warning('UMAP.mat not found in %s', baseDir);
        return;
    end

    U = load(umapFile, ...
        'origDownsampEMGInd', ...
        'classifierLabels', ...
        'classifierBehvs');

    if ~isfield(U, 'origDownsampEMGInd') || isempty(U.origDownsampEMGInd)
        warning('origDownsampEMGInd missing/empty in UMAP.mat; cannot align labels.');
        return;
    end

    if ~isfield(U, 'classifierLabels') || isempty(U.classifierLabels)
        warning('classifierLabels missing; cannot build classifier labels.');
        return;
    end

    if ~isfield(U, 'classifierBehvs') || isempty(U.classifierBehvs)
        warning('classifierBehvs missing; cannot remap classifier labels to canonical.');
        return;
    end

    origInd = U.origDownsampEMGInd(:);
    classifierLabels = U.classifierLabels(:);
    classifierBehvs = U.classifierBehvs;

    % canonical behavior name list
    manBehvNames = {'climbdown','climbup','eating','grooming', ...
                    'jumpdown','jumping','rearing','still','walkflat','walkgrid'};
    meta.manBehvNames = manBehvNames;

    % lookup table for alternate behavior names across animals
    canonicalLookup = containers.Map;
    canonicalLookup('climbdown')  = 1;
    canonicalLookup('climbup')    = 2;
    canonicalLookup('eating')     = 3;
    canonicalLookup('eat')        = 3;
    canonicalLookup('grooming')   = 4;
    canonicalLookup('groom')      = 4;
    canonicalLookup('jumpdown')   = 5;
    canonicalLookup('jumping')    = 6;
    canonicalLookup('jumpacross') = 6;
    canonicalLookup('rearing')    = 7;
    canonicalLookup('rear')       = 7;
    canonicalLookup('still')      = 8;
    canonicalLookup('walkflat')   = 9;
    canonicalLookup('walkgrid')   = 10;

    % build remap: per-animal classifier index -> canonical index (0..10)
    nClassBehv = numel(classifierBehvs);
    classBehvNumbers = zeros(1, nClassBehv);

    for iBehv = 1:nClassBehv
        thisName = classifierBehvs{iBehv};
        cleanName = lower(strrep(strrep(thisName, ' ', ''), '_', ''));

        if isKey(canonicalLookup, cleanName)
            classBehvNumbers(iBehv) = canonicalLookup(cleanName);
        else
            classBehvNumbers(iBehv) = 0;
        end
    end

    meta.classifierBehvs = classifierBehvs;
    meta.classifierRemap = classBehvNumbers;

    % apply remap to reduced label vector
    labelVecReduced = nan(size(classifierLabels));
    for i = 1:numel(classifierLabels)
        v = classifierLabels(i);
        if isnan(v)
            continue;
        elseif v == 0
            labelVecReduced(i) = 0;
        else
            if v >= 1 && v <= numel(classBehvNumbers)
                labelVecReduced(i) = classBehvNumbers(v);
            else
                labelVecReduced(i) = nan;
            end
        end
    end

    % align reduced labels into full fr timeline using origDownsampEMGInd
    n = min(numel(origInd), numel(labelVecReduced));
    origInd = origInd(1:n);
    labelVecReduced = labelVecReduced(1:n);

    ok = origInd >= 1 & origInd <= Tfr & ~isnan(labelVecReduced);
    labels1k(origInd(ok)) = labelVecReduced(ok);

    meta.nReduced = numel(labelVecReduced);
    meta.nAligned = nnz(ok);
end

% =====================================================================
% helper: compute xc for two vectors by scanning lags (removes nans)
% =====================================================================
function [lagsSec, xc, peakLagSec, peakCorr] = computeManualXCorrVec(intVec, pyrVec, binSize, maxLagSecs)
    maxLagBins = round(maxLagSecs / binSize);
    lagsBins = -maxLagBins:maxLagBins;
    lagsSec = lagsBins * binSize;
    xc = nan(size(lagsBins));

    intVec = intVec(:)';
    pyrVec = pyrVec(:)';

    for li = 1:numel(lagsBins)
        lag = lagsBins(li);

        if lag < 0
            intSeg = intVec(1:end+lag);
            pyrSeg = pyrVec(1-lag:end);
        elseif lag > 0
            intSeg = intVec(1+lag:end);
            pyrSeg = pyrVec(1:end-lag);
        else
            intSeg = intVec;
            pyrSeg = pyrVec;
        end

        v = ~isnan(intSeg) & ~isnan(pyrSeg);
        if nnz(v) > 10
            x = intSeg(v);
            y = pyrSeg(v);
            xc(li) = corr(x(:), y(:));
        end
    end

    [peakCorr, peakIdx] = max(xc);
    if isempty(peakIdx) || isnan(peakCorr)
        peakLagSec = NaN;
    else
        peakLagSec = lagsSec(peakIdx);
    end
end

% =====================================================================
% helper: short label for sgtitle
% =====================================================================
function tag = shortTag(baseDir)
    [~, folderName] = fileparts(baseDir);
    m = regexp(folderName, 'D\d+', 'match', 'once');
    if isempty(m)
        tag = folderName;
    else
        tag = m;
    end
end
